---
title: "AR_forecasting"
author: "Krystal"
date: "`r Sys.Date()`"
output: html_document
---

## Relevant Libraries
```{r}
library(tidyverse)
library(stringr)
library(forecast)
```

## Load in PV Data 
```{r}
# Passenger Volume for Trains - By Origin Destination (2023 Dec)
pv_train_od_202312 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202312.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

# Passenger Volume for Trains - By Origin Destination (2024 Jan)
pv_train_od_202401 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202401.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

# Passenger Volume for Trains - By Origin Destination (2024 Feb)
pv_train_od_202402 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202402.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))
```

## Data Preprocessing 
```{r}
# Merge all Train By OD Passenger Volume data for Dec 2023 and Jan 2024 
combined_train_pv_od <- rbind(pv_train_od_202312, pv_train_od_202401) %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-")) %>%
  mutate(trip = as.factor(trip)) %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
combined_train_pv_od$YEAR_MONTH_HOUR = combined_train_pv_od$YEAR_MONTH
combined_train_pv_od$YEAR_MONTH_HOUR = as.POSIXct(paste(combined_train_pv_od$YEAR_MONTH_HOUR, combined_train_pv_od$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
combined_train_pv_od$Year <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%Y"))
combined_train_pv_od$Month <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%m"))
combined_train_pv_od$Hour <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%H"))
combined_train_pv_od$trip_numeric <- as.numeric(as.factor(combined_train_pv_od$trip))

str(combined_train_pv_od)


### Testing Data > Feb 2024
pv_train_od_202402 <- pv_train_od_202402 %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-")) %>%
  mutate(trip = as.factor(trip)) %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
pv_train_od_202402$YEAR_MONTH_HOUR = pv_train_od_202402$YEAR_MONTH
pv_train_od_202402$YEAR_MONTH_HOUR = as.POSIXct(paste(pv_train_od_202402$YEAR_MONTH_HOUR, pv_train_od_202402$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
pv_train_od_202402$Year <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%Y"))
pv_train_od_202402$Month <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%m"))
pv_train_od_202402$Hour <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%H"))
pv_train_od_202402$trip_numeric <- as.numeric(as.factor(pv_train_od_202402$trip))

```

```{r}
training <- combined_train_pv_od %>%
  select(trip, trip_numeric, YEAR_MONTH_HOUR, seasonal_dummy, TOTAL_TRIPS, Year, Month,Hour) %>%
  arrange(trip, Year, Month, Hour)

X <- data.frame( 
  Hour = as.integer(training$Hour),
  trip_numeric = as.numeric(training$trip_numeric)
  )

X_matrix <- as.matrix(X[, c("Hour", "trip_numeric")])

data <- combined_train_pv_od$TOTAL_TRIPS

ar_model <- Arima(data, order = c(2, 0, 0), xreg = X_matrix)
summary(ar_model)

test_data <- data.frame(
  Hour = as.integer(pv_train_od_202402$Hour),
  trip_numeric = as.numeric(pv_train_od_202402$trip_numeric)
)

X_matrix_test <- as.matrix(test_data[, c("Hour", "trip_numeric")])

forecast_result <- forecast(ar_model, xreg = X_matrix_test)

forecasted_values <- forecast_result$mean

actual_data <- pv_train_od_202402

mae <- mean(abs(forecasted_values - actual_data$TOTAL_TRIPS))

rmse <- sqrt(mean((forecasted_values - actual_data$TOTAL_TRIPS)^2))

# Compare forecasts with actual TOTAL_TRIPS
comparison_df <- data.frame(
  YEAR_MONTH_HOUR = actual_data$YEAR_MONTH_HOUR,
  Hour = actual_data$Hour, 
  Trip = actual_data$trip, 
  Actual = actual_data$TOTAL_TRIPS,
  Forecasted = forecasted_values
)


#install.packages("openxlsx")
library(openxlsx)

write.xlsx(comparison_df, file = "../PV Data [Buses and Trains]/Trains/By Train Station/forecast_ar.xlsx")

```










## If ignore End Destination >> IGNORE
```{r}
pv_train_od_202312 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202312.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

# Passenger Volume for Trains - By Origin Destination (2024 Jan)
pv_train_od_202401 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202401.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

# Passenger Volume for Trains - By Origin Destination (2024 Feb)
pv_train_od_202402 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202402.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))


pv_train_od_202312 <- pv_train_od_202312 %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
pv_train_od_202312$YEAR_MONTH_HOUR = pv_train_od_202312$YEAR_MONTH
pv_train_od_202312$YEAR_MONTH_HOUR = as.POSIXct(paste(pv_train_od_202312$YEAR_MONTH_HOUR, pv_train_od_202312$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
pv_train_od_202312$Year <- as.integer(format(pv_train_od_202312$YEAR_MONTH_HOUR, "%Y"))
pv_train_od_202312$Month <- as.integer(format(pv_train_od_202312$YEAR_MONTH_HOUR, "%m"))
pv_train_od_202312$Hour <- as.integer(format(pv_train_od_202312$YEAR_MONTH_HOUR, "%H"))

pv_train_od_202312$trip_numeric <- as.numeric(as.factor(pv_train_od_202312$ORIGIN_PT_CODE))


# only use Dec 2023 to train
training <- pv_train_od_202312 %>%
  group_by(ORIGIN_PT_CODE, trip_numeric, DAY_TYPE, TIME_PER_HOUR) %>%
  summarise(total_trips = sum(TOTAL_TRIPS))


pv_train_od_202402 <- pv_train_od_202402 %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
pv_train_od_202402$YEAR_MONTH_HOUR = pv_train_od_202402$YEAR_MONTH
pv_train_od_202402$YEAR_MONTH_HOUR = as.POSIXct(paste(pv_train_od_202402$YEAR_MONTH_HOUR, pv_train_od_202402$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
pv_train_od_202402$Year <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%Y"))
pv_train_od_202402$Month <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%m"))
pv_train_od_202402$Hour <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%H"))

pv_train_od_202402$trip_numeric <- as.numeric(as.factor(pv_train_od_202402$ORIGIN_PT_CODE))

testing <- pv_train_od_202402 %>%
  group_by(ORIGIN_PT_CODE, trip_numeric, DAY_TYPE, TIME_PER_HOUR) %>%
  summarise(total_trips = sum(TOTAL_TRIPS))


X_regressors <- data.frame( 
  Hour = as.integer(training$TIME_PER_HOUR),
  trip_numeric = as.numeric(training$trip_numeric)
  )

X_matrix <- as.matrix(X_regressors[, c("Hour", "trip_numeric")])

data <- training$total_trips

ar_model <- Arima(data, order = c(2, 0, 0), xreg = X_matrix)
summary(ar_model)

test_data <- data.frame(
  Hour = as.integer(testing$TIME_PER_HOUR),
  trip_numeric = as.numeric(testing$trip_numeric)
)

X_matrix_test <- as.matrix(test_data[, c("Hour", "trip_numeric")])

forecast_result <- forecast(ar_model, xreg = X_matrix_test)

forecasted_values <- forecast_result$mean

actual_data <- testing

mae <- mean(abs(forecasted_values - actual_data$total_trips)) ## MAE: 38.19458

rmse <- sqrt(mean((forecasted_values - actual_data$total_trips)^2)) ## RMSE: 95.0159

# compare forecasts with actual TOTAL_TRIPS
comparison_df <- data.frame(
  YEAR_MONTH_HOUR = actual_data$YEAR_MONTH_HOUR,
  Hour = actual_data$Hour, 
  Trip = actual_data$trip, 
  Actual = actual_data$TOTAL_TRIPS,
  Forecasted = forecasted_values
)

summary(forecasted_values)


library(openxlsx)
write.xlsx(comparison_df, file = "../forecast_ar.xlsx", rowNames = FALSE)
```

# IGNORE
```{r}
# Passenger Volume for Trains - By Train Stops (2023 Dec)
pv_train_202312_weekend <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202312.csv") %>%
  filter(DAY_TYPE == "WEEKENDS/HOLIDAY") 

pv_train_202312_weekday <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202312.csv") %>%
  filter(DAY_TYPE == "WEEKDAY") 

# Passenger Volume for Trains - By Train Stops (2024 Jan)
pv_train_202401_weekend <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202401.csv") %>%
  filter(DAY_TYPE == "WEEKENDS/HOLIDAY") 

pv_train_202401_weekday <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202401.csv") %>%
  filter(DAY_TYPE == "WEEKDAY") 

# Passenger Volume for Trains - By Train Stops (2024 Feb)
pv_train_202402_weekend <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202402.csv") %>%
  filter(DAY_TYPE == "WEEKENDS/HOLIDAY") 

pv_train_202402_weekday <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202402.csv") %>%
  filter(DAY_TYPE == "WEEKDAY") 



## By Station
training_weekend <- rbind(pv_train_202312_weekend, pv_train_202401_weekend) %>%
  select(-DAY_TYPE, -PT_TYPE, -TOTAL_TAP_OUT_VOLUME) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-"))) %>%
  rename( y = TOTAL_TAP_IN_VOLUME)

training_weekend$YEAR_MONTH_HOUR = training_weekend$YEAR_MONTH
training_weekend$YEAR_MONTH_HOUR = as.POSIXct(paste(training_weekend$YEAR_MONTH_HOUR, training_weekend$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
training_weekend$Year <- as.integer(format(training_weekend$YEAR_MONTH_HOUR, "%Y"))
training_weekend$Month <- as.integer(format(training_weekend$YEAR_MONTH_HOUR, "%m"))
training_weekend$Hour <- as.integer(format(training_weekend$YEAR_MONTH_HOUR, "%H"))

training_weekend <- training_weekend %>%
  mutate( PT_CODE = as.factor(PT_CODE)) %>%
  select(-YEAR_MONTH, -Year, -Month, -TIME_PER_HOUR) %>%
  arrange(PT_CODE, Hour)

str(training_weekend)

testing_weekend <- pv_train_202402_weekend %>%
  select(-DAY_TYPE, -PT_TYPE, -TOTAL_TAP_OUT_VOLUME) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-"))) %>%
  rename( y = TOTAL_TAP_IN_VOLUME)

testing_weekend$YEAR_MONTH_HOUR = testing_weekend$YEAR_MONTH
testing_weekend$YEAR_MONTH_HOUR = as.POSIXct(paste(testing_weekend$YEAR_MONTH_HOUR, testing_weekend$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
testing_weekend$Year <- as.integer(format(testing_weekend$YEAR_MONTH_HOUR, "%Y"))
testing_weekend$Month <- as.integer(format(testing_weekend$YEAR_MONTH_HOUR, "%m"))
testing_weekend$Hour <- as.integer(format(testing_weekend$YEAR_MONTH_HOUR, "%H"))


testing_weekend <- testing_weekend %>%
  mutate( PT_CODE = as.factor(PT_CODE)) %>%
  select(-YEAR_MONTH, -Year, -Month, -TIME_PER_HOUR) %>%
  arrange(PT_CODE, Hour)
```


## Data Preprocessing 
```{r}
# Merge all Train By OD Passenger Volume data for Dec 2023 and Jan 2024 
combined_train_pv_od <- rbind(pv_train_od_202312, pv_train_od_202401) %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-")) %>%
  mutate(trip = as.factor(trip)) %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
combined_train_pv_od$YEAR_MONTH_HOUR = combined_train_pv_od$YEAR_MONTH
combined_train_pv_od$YEAR_MONTH_HOUR = as.POSIXct(paste(combined_train_pv_od$YEAR_MONTH_HOUR, combined_train_pv_od$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
combined_train_pv_od$Year <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%Y"))
combined_train_pv_od$Month <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%m"))
combined_train_pv_od$Hour <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%H"))
combined_train_pv_od$trip_numeric <- as.numeric(as.factor(combined_train_pv_od$trip))

str(combined_train_pv_od)


### Testing Data > Feb 2024
pv_train_od_202402 <- pv_train_od_202402 %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-")) %>%
  mutate(trip = as.factor(trip)) %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
pv_train_od_202402$YEAR_MONTH_HOUR = pv_train_od_202402$YEAR_MONTH
pv_train_od_202402$YEAR_MONTH_HOUR = as.POSIXct(paste(pv_train_od_202402$YEAR_MONTH_HOUR, pv_train_od_202402$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
pv_train_od_202402$Year <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%Y"))
pv_train_od_202402$Month <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%m"))
pv_train_od_202402$Hour <- as.integer(format(pv_train_od_202402$YEAR_MONTH_HOUR, "%H"))
pv_train_od_202402$trip_numeric <- as.numeric(as.factor(pv_train_od_202402$trip))
```

## IGNORE
```{r}
## By Station
new_data <- training_weekend$y

new_X <- data.frame(
  PT_CODE = as.numeric(training_weekend$PT_CODE),
  TIME = as.numeric(training_weekend$YEAR_MONTH_HOUR)
)

new_X_matrix <- as.matrix(new_X[, c("PT_CODE", "TIME")])

ar_model <- auto.arima(new_data, xreg=new_X_matrix)

summary(ar_model)

test_data <- data.frame(
  PT_CODE = as.numeric(testing_weekend$PT_CODE),
  TIME = as.numeric(testing_weekend$YEAR_MONTH_HOUR)
)

X_matrix_test <- as.matrix(test_data[, c("PT_CODE", "TIME")])

forecast_result <- forecast(ar_model, xreg = X_matrix_test)

forecasted_values <- forecast_result$mean


fit_arima <- function(data, order, xreg) {
  ar_model <- Arima(data, order = c(order, 0, 0), xreg = X_matrix)
  return(AIC(ar_model))
}

lags <- 10:15  # current best lag of 10

aic_values <- numeric(length(lags))

# fit diff lags to model
for (i in seq_along(lags)) {
  aic_values[i] <- fit_arima(data, lags[i], new_X_matrix)
}

best_lag <- lags[which.min(aic_values)]
best_lag <- 2

# order parameter specifies order(number of lags, order of difference, number of moving average components) - set to 0 for standard AR >> change accordingly 

ar_model <- Arima(new_data, order = c(best_lag, 0, 0), xreg = new_X_matrix)
summary(ar_model)

forecast_result <- forecast(ar_model)

print(forecast_result)

ns <- training_weekend %>%
  filter(PT_CODE == "NS7") %>%
  arrange(YEAR_MONTH_HOUR)
```


## IGNORE
```{r}
data <- combined_train_pv_od$TOTAL_TRIPS


X <- data.frame(
  Year = as.numeric(combined_train_pv_od$Year),
  Month = as.integer(combined_train_pv_od$Month),
  Hour = as.integer(combined_train_pv_od$Hour),
  seasonal_dummy = as.integer(combined_train_pv_od$seasonal_dummy),
  trip_numeric = as.numeric(combined_train_pv_od$trip_numeric)
)

str(X)

X_matrix <- as.matrix(X[, c("Year", "Month", "Hour", "seasonal_dummy", "trip_numeric")])

ar_model <- auto.arima(data, xreg = X_matrix)


summary(ar_model)

test_data <- data.frame(
  Year = as.numeric(pv_train_od_202402$Year),
  Month = as.integer(pv_train_od_202402$Month),
  Hour = as.integer(pv_train_od_202402$Hour),
  seasonal_dummy = as.integer(pv_train_od_202402$seasonal_dummy),
  trip_numeric = as.numeric(pv_train_od_202402$trip_numeric)
)

X_matrix_test <- as.matrix(test_data[, c("Year", "Month", "Hour", "seasonal_dummy", "trip_numeric")])

forecast_result <- forecast(ar_model, xreg = X_matrix_test)

forecasted_values <- forecast_result$mean
```

```{r}
actual_data <- pv_train_od_202402$TOTAL_TRIPS
actual_data <- pv_train_od_202402

forecasted_values <- forecast_result$mean

mae <- mean(abs(forecasted_values - actual_data))

rmse <- sqrt(mean((forecasted_values - actual_data)^2))

# compare forecasts with actual TOTAL_TRIPS
comparison_df <- data.frame(
  Trip = actual_data$trip, 
  Actual = actual_data$TOTAL_TRIPS,
  Forecasted = forecasted_values
)
```


## ACTUAL
```{r}
### new
training <- combined_train_pv_od %>%
  select(trip, trip_numeric, YEAR_MONTH_HOUR, seasonal_dummy, TOTAL_TRIPS, Year, Month,Hour) %>%
  arrange(trip, Year, Month, Hour)


X <- data.frame( 
  Hour = as.integer(training$Hour),
  trip_numeric = as.numeric(training$trip_numeric)
  )

X_matrix <- as.matrix(X[, c("Hour", "trip_numeric")])
```

## ACTUAL
```{r}
## new
data <- combined_train_pv_od$TOTAL_TRIPS
ar_model <- Arima(data, order = c(2, 0, 0), xreg = X_matrix)
summary(ar_model)

test_data <- data.frame(
  Hour = as.integer(pv_train_od_202402$Hour),
  trip_numeric = as.numeric(pv_train_od_202402$trip_numeric)
)

X_matrix_test <- as.matrix(test_data[, c("Hour", "trip_numeric")])

forecast_result <- forecast(ar_model, xreg = X_matrix_test)

forecasted_values <- forecast_result$mean

#actual_data <- pv_train_od_202402$TOTAL_TRIPS
actual_data <- pv_train_od_202402

mae <- mean(abs(forecasted_values - actual_data$TOTAL_TRIPS))

rmse <- sqrt(mean((forecasted_values - actual_data$TOTAL_TRIPS)^2))

# compare forecasts with actual TOTAL_TRIPS
comparison_df <- data.frame(
  YEAR_MONTH_HOUR = actual_data$YEAR_MONTH_HOUR,
  Hour = actual_data$Hour, 
  Trip = actual_data$trip, 
  Actual = actual_data$TOTAL_TRIPS,
  Forecasted = forecasted_values
)


#install.packages("openxlsx")
library(openxlsx)

write.xlsx(comparison_df, file = "../PV Data [Buses and Trains]/Trains/By Train Station/forecast_ar.xlsx")
```


##### LATEST >> IGNORE
### splitting with split index 
```{r}
library(tidyverse)
library(stringr)
library(forecast)

# Passenger Volume for Trains - By Origin Destination (2023 Dec)
pv_train_od_202312 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202312.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

# Passenger Volume for Trains - By Origin Destination (2024 Jan)
pv_train_od_202401 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202401.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

# Passenger Volume for Trains - By Origin Destination (2024 Feb)
pv_train_od_202402 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202402.csv") %>%
  mutate(seasonal_dummy = ifelse(DAY_TYPE == "WEEKENDS/HOLIDAY", 1, 
                                 ifelse(DAY_TYPE == "WEEKDAY", 0, NA)))

combined_train_pv_od <- rbind(pv_train_od_202312, pv_train_od_202401, pv_train_od_202402) %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-")) %>%
  mutate(trip = as.factor(trip)) %>%
  mutate(seasonal_dummy = as.factor(seasonal_dummy)) %>%
  mutate(ORIGIN_PT_CODE = as.factor(ORIGIN_PT_CODE)) %>%
  mutate(DESTINATION_PT_CODE = as.factor(DESTINATION_PT_CODE)) %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-")))
  
combined_train_pv_od$YEAR_MONTH_HOUR = combined_train_pv_od$YEAR_MONTH
combined_train_pv_od$YEAR_MONTH_HOUR = as.POSIXct(paste(combined_train_pv_od$YEAR_MONTH_HOUR, combined_train_pv_od$TIME_PER_HOUR), format = "%Y-%m-%d %H") 
combined_train_pv_od$Year <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%Y"))
combined_train_pv_od$Month <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%m"))
combined_train_pv_od$Hour <- as.integer(format(combined_train_pv_od$YEAR_MONTH_HOUR, "%H"))
combined_train_pv_od$trip_numeric <- as.numeric(as.factor(combined_train_pv_od$trip))

# Determine the split index
split_index <- 8500

combined_train_pv_od <- combined_train_pv_od %>%
  select(trip, trip_numeric, YEAR_MONTH_HOUR, seasonal_dummy, TOTAL_TRIPS, Year, Month,Hour) %>%
  arrange(trip, Year, Month, Hour)

training <- combined_train_pv_od[1:split_index, ]
testing <- combined_train_pv_od[(split_index + 1):10000, ]


X_regressors <- data.frame( 
  Hour = as.integer(training$Hour),
  trip_numeric = as.numeric(training$trip_numeric)
  )

X_matrix <- as.matrix(X_regressors[, c("Hour", "trip_numeric")])

data <- training$TOTAL_TRIPS

ar_model <- Arima(data, order = c(2, 0, 0), xreg = X_matrix)
summary(ar_model)

test_data <- data.frame(
  Hour = as.integer(testing$Hour),
  trip_numeric = as.numeric(testing$trip_numeric)
)

X_matrix_test <- as.matrix(test_data[, c("Hour", "trip_numeric")])

forecast_result <- forecast(ar_model, xreg = X_matrix_test)

forecasted_values <- forecast_result$mean

actual_data <- testing

mae <- mean(abs(forecasted_values - actual_data$TOTAL_TRIPS)) ## MAE: 38.19458

rmse <- sqrt(mean((forecasted_values - actual_data$TOTAL_TRIPS)^2)) ## RMSE: 95.0159

# compare forecasts with actual TOTAL_TRIPS
comparison_df <- data.frame(
  YEAR_MONTH_HOUR = actual_data$YEAR_MONTH_HOUR,
  Hour = actual_data$Hour, 
  Trip = actual_data$trip, 
  Actual = actual_data$TOTAL_TRIPS,
  Forecasted = forecasted_values
)

summary(forecasted_values)


library(openxlsx)
write.xlsx(comparison_df, file = "../forecast_ar.xlsx", rowNames = FALSE)
```

### Time Series and Residual Plot
```{r}
str(comparison_df)

ts_predicted <- ts(forecast_result$mean, start = start(actual_data$TOTAL_TRIPS), frequency = frequency(actual_data$TOTAL_TRIPS))

# Plot the actual values
plot(actual_data$TIME_PER_HOUR, actual_data$TOTAL_TRIPS, main = "Actual vs Predicted", xlab = "Time", ylab = "Total Trips", col = "blue")

lines(forecasted_values, col = "red")


# Add a legend
legend("topleft", legend = c("Actual", "Predicted"), col = c("blue", "red"), lty = 1)
```


### ROC Curve
```{r}
# Load the ggplot2 library
library(ggplot2)

combined_data <- data.frame(
  TIME_PER_HOUR = c(actual_data$TIME_PER_HOUR, actual_data$TIME_PER_HOUR),
  TOTAL_TRIPS = c(actual_data$TOTAL_TRIPS, forecasted_values),
  Type = rep(c("Actual", "Forecasted"), each = length(actual_data$TIME_PER_HOUR))
)

# Create the plot with separate aesthetics for lines and points
ggplot(combined_data, aes(x = TIME_PER_HOUR, y = TOTAL_TRIPS, color = Type)) +
  geom_point(data = combined_data[combined_data$Type == "Actual", ], shape = 1, size = 3) +
  geom_line(data = combined_data[combined_data$Type == "Forecasted", ], aes(group = 1), color = "red") +
  labs(title = "Actual vs Forecasted",
       x = "Time",
       y = "Total Trips") +
  scale_color_manual(values = c("Actual" = "blue", "Forecasted" = "red")) +
  guides(color = guide_legend(title = "Data Type")) +
  theme(legend.position = "right") 
```
