---
title: "SARIMA"
author: "Eliza"
date: "2024-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE)
```

### Load Packages
```{r}
library(tidyverse)
library(lubridate)
library(forecast)
```

## redo
```{r}
testing <- read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202402.csv")
node_202401 = read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202401.csv")
node_202312 = read.csv("../PV Data [Buses and Trains]/Trains/By Train Station/transport_node_train_202312.csv")

training = rbind(node_202312,node_202401)

training_weekday = training %>%
  select(-PT_TYPE) %>%
  select(-YEAR_MONTH) %>%
  select(-TOTAL_TAP_OUT_VOLUME) %>%
  filter(DAY_TYPE == "WEEKDAY") %>%
  select(-DAY_TYPE) %>%
  rename(y = TOTAL_TAP_IN_VOLUME) %>%
  arrange(PT_CODE,TIME_PER_HOUR) %>%
  mutate(PT_CODE = as.numeric(factor(PT_CODE)))

testing_weekday = testing %>%
  select(-PT_TYPE) %>%
  select(-YEAR_MONTH) %>%
  select(-TOTAL_TAP_OUT_VOLUME) %>%
  filter(DAY_TYPE == "WEEKDAY") %>%
  select(-DAY_TYPE) %>%
  arrange(PT_CODE,TIME_PER_HOUR) %>%
  rename(y = TOTAL_TAP_IN_VOLUME) %>%
  mutate(PT_CODE = as.numeric(factor(PT_CODE)))

testing_weekend = testing %>%
  select(-PT_TYPE) %>%
  select(-YEAR_MONTH) %>%
  select(-TOTAL_TAP_OUT_VOLUME) %>%
  filter(DAY_TYPE == "WEEKENDS/HOLIDAY") %>%
  select(-DAY_TYPE) %>%
  arrange(PT_CODE,TIME_PER_HOUR) %>%
  rename(y = TOTAL_TAP_IN_VOLUME) %>%
  mutate(PT_CODE = as.numeric(factor(PT_CODE)))

training_weekend = training %>%
  select(-PT_TYPE) %>%
  select(-YEAR_MONTH) %>%
  select(-TOTAL_TAP_OUT_VOLUME) %>%
  filter(DAY_TYPE == "WEEKENDS/HOLIDAY") %>%
  select(-DAY_TYPE) %>%
  arrange(PT_CODE,TIME_PER_HOUR) %>%
  rename(y = TOTAL_TAP_IN_VOLUME) %>%
  mutate(PT_CODE = as.numeric(factor(PT_CODE)))
```

```{r}
ts_data_weekday <- ts(training_weekday$y, frequency = 20) #change to time series with hourly seasonality
# Fit the SARIMA model
# Define your additional regressors
additional_regressors <- training_weekday$PT_CODE

future_regressors <- testing_weekday$PT_CODE

fit <- auto.arima(ts_data_weekday, seasonal = TRUE)
print(fit) #ARIMA (2,1,0)(1,0,0)

# Fit the model with additional regressors
fit <- Arima(ts_data_weekday, order=c(5,1,1), seasonal=c(0,0,1), xreg=additional_regressors)
```

## Testing 
```{r}
# Generate forecasts
forecasts_weekday <- forecast(fit, xreg=future_regressors,h = 3410)

# Compare forecasts to actual test data
test_results <- data.frame(
  Actual = testing_weekday$y,
  Predicted = forecasts_weekday$mean
)

# Calculate error metrics
RMSE <- sqrt(mean((test_results$Actual - test_results$Predicted)^2))

print(paste("Root Mean Squared Error: ", RMSE))
```





# v1
## Restructuring Data
```{r}
# Passenger Volume for Trains - By Origin Destination (2023 Dec)
pv_train_od_202312 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202312.csv")
#pv_train_od_202312 = pv_train_od_202312 %>%
#  mutate(month = substring(YEAR_MONTH,6,7))

# Passenger Volume for Trains - By Origin Destination (2024 Jan)
pv_train_od_202401 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202401.csv")
#pv_train_od_202401 = pv_train_od_202401 %>%
#  mutate(month = substring(YEAR_MONTH,6,7))

# Passenger Volume for Trains - By Origin Destination (2024 Feb)
pv_train_od_202402 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202402.csv")
#pv_train_od_202402 = pv_train_od_202402 %>%
#  mutate(month = substring(YEAR_MONTH,6,7))

# combine data from Dec 2023 - Feb 2024 of passenger volume for trains with origin destinations
pv_train_od = rbind(pv_train_od_202312,pv_train_od_202401)
testing = pv_train_od_202402

# Combine date and hour
pv_train_od$ds <- as.POSIXct(paste(pv_train_od$ds, pv_train_od$TIME_PER_HOUR), format = "%Y-%m-%d %H")

# combine data from Dec 2023 - Feb 2024 of passenger volume for trains with origin destinations
pv_train_od = rbind(pv_train_od_202312,pv_train_od_202401)
testing = pv_train_od_202402
# change class of date to Date
pv_train_od = pv_train_od %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-"))) %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-"))

testing = testing %>%
  mutate(YEAR_MONTH = as.Date(paste(YEAR_MONTH,"01",sep = "-"))) %>%
  mutate(trip = str_c(ORIGIN_PT_CODE, DESTINATION_PT_CODE, sep="-"))

#converting everything to numeric
pv_train_od$y = pv_train_od$TOTAL_TRIPS
pv_train_od$trip <- as.numeric(factor(pv_train_od$trip))
pv_train_od$ORIGIN_PT_CODE <- as.numeric(factor(pv_train_od$ORIGIN_PT_CODE))
pv_train_od$DESTINATION_PT_CODE <- as.numeric(factor(pv_train_od$DESTINATION_PT_CODE))
pv_train_od$DAY_TYPE <- as.numeric(factor(pv_train_od$DAY_TYPE))

testing$y = testing$TOTAL_TRIPS
testing$trip <- as.numeric(factor(testing$trip))
testing$ORIGIN_PT_CODE <- as.numeric(factor(testing$ORIGIN_PT_CODE))
testing$DESTINATION_PT_CODE <- as.numeric(factor(testing$DESTINATION_PT_CODE))
testing$DAY_TYPE <- as.numeric(factor(testing$DAY_TYPE))
pv_train_od$ds = pv_train_od$YEAR_MONTH
testing$ds = testing$YEAR_MONTH


pv_train_od = pv_train_od %>%
  select(-YEAR_MONTH) %>%
  select(-TIME_PER_HOUR) %>%
  select(-PT_TYPE) %>%
  select(-ORIGIN_PT_CODE) %>%
  select(-DESTINATION_PT_CODE) %>%
  arrange(ds,trip)


```

```{r}
ts_data <- ts(pv_train_od$TOTAL_TRIPS, frequency = 20) #change to time series with hourly seasonality
# Fit the SARIMA model
# Define your additional regressors
additional_regressors <- cbind(pv_train_od$DAY_TYPE, pv_train_od$trip)

future_regressors <- cbind(testing$DAY_TYPE, testing$trip)

#fit <- auto.arima(ts_data, seasonal = TRUE)

# Fit the model with additional regressors
fit <- Arima(ts_data, order=c(2,1,1), seasonal=c(0,0,2), xreg=additional_regressors)
```

## Testing 
```{r}
# Generate forecasts
forecasts <- forecast(fit, xreg=future_regressors,h = 804012)

# Compare forecasts to actual test data
test_results <- data.frame(
  Actual = testing$TOTAL_TRIPS,
  Predicted = forecasts$mean
)

# Calculate error metrics
RMSE <- sqrt(mean((test_results$Actual - test_results$Predicted)^2))

print(paste("Root Mean Squared Error: ", RMSE))
sarima = data.frame(forecasts[["mean"]])
write_xlsx(sarima, "../PV Data [Buses and Trains]/Trains/By Train Station/forecast_sarima_2lags.xlsx")
```

## Plotting
```{r}
# Create a time series object for the predicted values
ts_predicted <- ts(forecasts$mean, start = start(testing$TOTAL_TRIPS), frequency = frequency(testing$TOTAL_TRIPS))

# Plot the actual values
plot(testing$TIME_PER_HOUR, testing$TOTAL_TRIPS, main = "Actual vs Predicted", xlab = "Time", ylab = "Total Trips", col = "blue")

# Add the predicted values to the plot
lines(forecasts$TIME_PER_HOUR, col = "red")

# Add a legend
legend("topleft", legend = c("Actual", "Predicted"), col = c("blue", "red"), lty = 1)

```


# V3
```{r}
# Passenger Volume for Trains - By Train Stops (2024 Jan)
pv_train_202401 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202401.csv")

# Passenger Volume for Trains - By Train Stops (2024 Feb)
test_202402 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202402.csv")


# Passenger Volume for Trains - By Origin Destination (2023 Dec)
pv_train_202312 <- read.csv("../PV Data [Buses and Trains]/Trains/By OD/origin_destination_train_202312.csv")

train_combined <- rbind(pv_train_202312, pv_train_202401, test_202402)

# Assuming the first day of each month for the YEAR_MONTH column
train_combined$YEAR_MONTH <- as.Date(paste0(train_combined$YEAR_MONTH, "-01"))

# Drop the specified columns from the training dataset
train_combined <- train_combined %>%
  select(-DESTINATION_PT_CODE, -ORIGIN_PT_CODE, -PT_TYPE, -DAY_TYPE, -YEAR_MONTH)

# Selecting the first 10,000 rows for both features and target variable
subset_data <- train_combined_encoded[1:10000, ]
X_subset <- as.matrix(subset_data[, setdiff(names(subset_data), "TOTAL_TRIPS")])
y_subset <- subset_data[["TOTAL_TRIPS"]]

# Reshape input to be 3D [samples, time steps, features] for LSTM
X_subset_array <- array(X_subset, dim = c(nrow(X_subset), 1, ncol(X_subset)))


# Determine the split index
split_index <- 8500

# Split the features and target into training and testing sets
X_train_subset <- X_subset[1:split_index, ]
y_train_subset <- y_subset[1:split_index]

X_test_subset <- X_subset[(split_index + 1):10000, ]
y_test_subset <- y_subset[(split_index + 1):10000]
```

```{r}
ts_data <- ts(y_train_subset, frequency = 20) #change to time series with hourly seasonality
# Fit the SARIMA model
# Define your additional regressors
additional_regressors <- cbind(pv_train_od$DAY_TYPE, pv_train_od$trip)

future_regressors <- cbind(testing$DAY_TYPE, testing$trip)

fit <- auto.arima(ts_data, seasonal = TRUE)
print(fit) #ARIMA (5,1,1)(0,0,2)

# Fit the model with additional regressors
fit <- Arima(ts_data, order=c(2,1,1), seasonal=c(0,0,2), xreg=additional_regressors)
```

## Testing 
```{r}
# Generate forecasts
forecasts <- forecast(fit, xreg=future_regressors,h = 804012)

# Compare forecasts to actual test data
test_results <- data.frame(
  Actual = testing$TOTAL_TRIPS,
  Predicted = forecasts$mean
)

# Calculate error metrics
RMSE <- sqrt(mean((test_results$Actual - test_results$Predicted)^2))

print(paste("Root Mean Squared Error: ", RMSE))
sarima = data.frame(forecasts[["mean"]])
write_xlsx(sarima, "../PV Data [Buses and Trains]/Trains/By Train Station/forecast_sarima_v3.xlsx")
```